from pathlib import Path

from scripts.command_inventory import inventory_commands, refresh_commands_category
from scripts.ollama_autonomous_agent import sanitize_documentation_text


def test_inventory_finds_commands_and_command_named_markdown(tmp_path: Path):
    (tmp_path / "runbook.md").write_text("```bash\npython scripts/check.py\n```\n", encoding="utf-8")
    (tmp_path / "terminal-notes.md").write_text("No executable example here.\n", encoding="utf-8")
    result = inventory_commands(tmp_path)
    assert result["markdown_files_with_commands"][0]["path"] == "runbook.md"
    named_paths = {item["path"] for item in result["markdown_files_named_for_commands"]}
    assert named_paths == {"runbook.md", "terminal-notes.md"}


def test_refresh_commands_category_is_deterministic(tmp_path: Path):
    (tmp_path / "ALLMDFILESREFS.md").write_text("# Inventory\n\n## Commands\nold\n", encoding="utf-8")
    (tmp_path / "runbook.md").write_text("```bash\npython scripts/check.py\n```\n", encoding="utf-8")
    result = refresh_commands_category(tmp_path)
    text = (tmp_path / "ALLMDFILESREFS.md").read_text(encoding="utf-8")
    assert result["inventory"]["command_count"] == 1
    assert "## Commands" in text
    assert "python scripts/check.py" in text
    assert "old" not in text


def test_generated_documentation_removes_engine_attribution():
    result = sanitize_documentation_text("Generated by the Ollama autonomous agent. Ollama ran this file.")
    assert "ollama" not in result.lower()
    assert "autonomous development agent" in result