"""Fail-closed audit for remotecompletion.md requirements and preflight gates."""
from __future__ import annotations

import json
import re
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


REMOTE_REQUIRED = {
    6, 7, 8, 9, 15, 16, 17, 18, 22, 23, 24, 25, 26, 30, 31, 32, 33, 34,
    37, 38, 39, 40, 41, 42, 43, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
    55, 56, 67, 68, 69, 70, 71, 74, 75, 76, 84, 85, 86, 87, 88, 89, 90,
    94, 95, 96, 98, 99, 101, 103, 104, 105, 108, 109, 110, 115, 116, 117,
    118, 120, 121, 122, 123, 124, 125, 126, 128, 129, 130,
}
LOCAL_READY = {
    1, 2, 3, 4, 5, 10, 11, 12, 13, 14, 19, 20, 21, 27, 28, 29, 35, 36,
    44, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 72, 73, 77, 78, 79, 80,
    81, 82, 83, 91, 92, 93, 97, 100, 102, 106, 107, 111, 112, 113, 114,
    119, 127,
}


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def _headings(path: Path) -> list[dict[str, Any]]:
    text = path.read_text(encoding="utf-8", errors="replace")
    matches = list(re.finditer(r"^##\s+(\d+)\.\s+(.+)$", text, re.MULTILINE))
    return [{"number": int(match.group(1)), "title": match.group(2).strip()} for match in matches if int(match.group(1)) <= 130]


def _remote_auth(root: Path) -> dict[str, Any]:
    checks = {}
    for repository in ("thealphakenya/Alpha-Q-ai", "thealphakenya/qmoi-enhanced"):
        repository_key = repository.rsplit("/", 1)[-1].replace("-", "_")
        for label, endpoint in (
            ("actions", f"repos/{repository}/actions/permissions"),
            ("protection", f"repos/{repository}/branches/main/protection"),
        ):
            result = subprocess.run(
                ["gh", "api", endpoint, "--silent"],
                cwd=root,
                capture_output=True,
                text=True,
                check=False,
                timeout=30,
            )
            checks[f"{repository_key}_{label}"] = {
                "returncode": result.returncode,
                "error_class": "403" if "403" in result.stderr else None,
            }
    return checks


def audit(root: Path | str) -> dict[str, Any]:
    base = Path(root).resolve()
    requirements = []
    for item in _headings(base / "remotecompletion.md"):
        number = item["number"]
        if number in REMOTE_REQUIRED:
            status = "BLOCKED_AUTH" if number in {6, 7, 8, 9, 15, 16, 17, 22, 23, 24, 49, 50, 51, 52, 56, 98, 99, 103, 104, 105, 108, 109, 128, 129, 130} else "REMOTE_REQUIRED"
            next_action = "Obtain authorized target-owned workflow access and collect terminal remote evidence."
        elif number in LOCAL_READY:
            status = "LOCAL_READY"
            next_action = "Keep evidence fresh; local readiness does not prove remote completion."
        else:
            status = "REVIEW_REQUIRED"
            next_action = "Inspect implementation and add independent evidence before marking complete."
        requirements.append({**item, "status": status, "next_action": next_action})
    return {
        "schema_version": "1.0",
        "generated_at": _utc_now(),
        "repository": "thealphakenya/Alpha-Q-ai",
        "requirements": requirements,
        "counts": {status: sum(item["status"] == status for item in requirements) for status in {item["status"] for item in requirements}},
        "preflight": _remote_auth(base),
        "completion": "BLOCKED_AUTH",
        "next_action": "Resolve authorization, then execute and independently verify target-owned workflows for every REMOTE_REQUIRED or BLOCKED_AUTH item.",
    }


def write_report(root: Path | str) -> Path:
    base = Path(root).resolve()
    report = audit(base)
    path = base / "ollamatracks" / "runbook_audit.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    _refresh_runbook_status(base, report)
    return path


def _refresh_runbook_status(root: Path, report: dict[str, Any]) -> None:
    runbook = root / "remotecompletion.md"
    text = runbook.read_text(encoding="utf-8")
    marker = "\n## Live Requirement Status (generated)\n"
    prefix = text.split(marker, 1)[0].rstrip()
    lines = [
        marker.rstrip(),
        "",
        "Generated by `scripts/runbook_audit.py`; `[x] LOCAL_READY` is not remote completion.",
        "",
        f"- Generated: `{report['generated_at']}`",
        f"- Completion state: `{report['completion']}`",
        f"- Counts: `{report['counts']}`",
        "",
    ]
    for item in report["requirements"]:
        mark = "x" if item["status"] == "LOCAL_READY" else "!"
        lines.append(f"- [{mark}] **{item['number']}. {item['title']}** — `{item['status']}`. {item['next_action']}")
    lines.extend(["", "## Live Preflight Status (generated)", ""])
    lines.extend([
        "Each preflight item is marked from the current local/remote evidence. `BLOCKED_AUTH` and `REMOTE_REQUIRED` remain incomplete.",
        "",
        "- [!] authenticated identity verified — `REMOTE_REQUIRED`; current CLI identity is known but target capabilities are limited.",
        "- [!] both repository identities verified — `REMOTE_REQUIRED`; independent target access is not fully proven.",
        "- [!] default branches verified remotely — `REMOTE_REQUIRED`; remote authorization is incomplete.",
        "- [!] current remote SHAs captured — `REMOTE_REQUIRED`; branch movement must be refreshed after authorization.",
        "- [x] local/remote divergence classified — `LOCAL_READY`; current status reports hosted movement and preserves the dirty worktree.",
        "- [!] peer repository access verified — `BLOCKED_AUTH`.",
        "- [!] Codespace cross-repository permissions verified — `BLOCKED_AUTH`.",
        "- [!] Actions read/dispatch capability verified for both repositories — `BLOCKED_AUTH`; target Actions endpoints must return authorized evidence.",
        "- [!] PR/check/release/artifact capability verified — `REMOTE_REQUIRED`.",
        "- [!] rulesets/protection inspected for both repositories — `BLOCKED_AUTH`; target protection endpoints must return authorized evidence.",
        "- [x] workflow files and triggers verified locally — `LOCAL_READY`; remote execution remains unproven.",
        "- [x] correlation ID created — `LOCAL_READY`; evidence uses the active completion correlation ID.",
        "- [x] active user edits detected — `LOCAL_READY`; dirty changes are preserved.",
        "- [x] locks checked — `LOCAL_READY`; control-plane audit is READY.",
        "- [x] bandwidth mode selected — `LOCAL_READY`; metadata-first/mobile defaults are active.",
        "- [x] resource budget checked locally — `LOCAL_READY`; heavy operations remain delegated remotely.",
        "- [x] current evidence freshness checked — `LOCAL_READY`; generated timestamps are recorded.",
        "- [!] both trees independently inventoried — `REMOTE_REQUIRED`.",
        "- [!] ownership map loaded — `REMOTE_REQUIRED`.",
        "- [x] changed paths identified — `LOCAL_READY`.",
        "- [x] destructive changes excluded — `LOCAL_READY`.",
        "- [x] synchronization plan recorded — `LOCAL_READY`.",
        "- [x] snapshot recorded — `LOCAL_READY`.",
        "- [!] target branch policy identified — `BLOCKED_AUTH`.",
        "- [!] PR exists in target repository — `REMOTE_REQUIRED`.",
        "- [!] PR head SHA recorded — `REMOTE_REQUIRED`.",
        "- [!] required checks correspond to current SHA — `REMOTE_REQUIRED`.",
        "- [!] required reviews satisfied — `BLOCKED_AUTH`.",
        "- [!] merge queue/ruleset requirements satisfied — `BLOCKED_AUTH`.",
        "- [x] no unresolved local merge conflict — `LOCAL_READY`; remote merge conflict state remains unproven.",
        "- [x] no stale local plan condition — `LOCAL_READY`; remote freshness still requires re-read.",
        "- [!] merge SHA verified — `REMOTE_REQUIRED`.",
        "- [!] build succeeded from intended SHA — `REMOTE_REQUIRED`.",
        "- [!] artifact hashes recorded — `REMOTE_REQUIRED`.",
        "- [!] installation test passed — `REMOTE_REQUIRED`.",
        "- [!] runtime test passed — `REMOTE_REQUIRED`.",
        "- [!] release publication verified — `REMOTE_REQUIRED`.",
        "- [!] release assets independently retrievable — `REMOTE_REQUIRED`.",
        "- [!] deployment source SHA verified — `REMOTE_REQUIRED`.",
        "- [!] environment requirements satisfied — `REMOTE_REQUIRED`.",
        "- [!] deployment terminal state verified — `REMOTE_REQUIRED`.",
        "- [!] health endpoint/runtime evidence verified — `REMOTE_REQUIRED`.",
        "- [!] Alpha-Q-ai main SHA verified — `REMOTE_REQUIRED`.",
        "- [!] qmoi-enhanced main SHA verified — `BLOCKED_AUTH`.",
        "- [!] backup parity verified — `REMOTE_REQUIRED`.",
        "- [x] Markdown inventory fresh locally — `LOCAL_READY`; remote publication is not proven.",
        "- [x] validation ledger fresh locally — `LOCAL_READY`.",
        "- [x] release ledger freshness checked locally — `LOCAL_READY`; release publication remains unproven.",
        "- [x] merge ledger freshness checked locally — `LOCAL_READY`; remote merge remains unproven.",
        "- [x] evidence ledger structurally valid — `LOCAL_READY`.",
        "- [!] no mandatory gate is UNKNOWN/STALE — `REMOTE_REQUIRED`.",
        "- [!] all blockers resolved or explicitly terminal — `BLOCKED_AUTH`.",
        "- [!] final verifier independently reread remote state — `BLOCKED_AUTH`.",
    ])
    runbook.write_text(prefix + "\n\n" + "\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    root = Path(__file__).resolve().parents[1]
    report_path = write_report(root)
    print(report_path.read_text(encoding="utf-8"))